# Site
name: William Harper
description: Research and Development
meta_description: "Will Harper R&D."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: 
#email: 'wowthemesnet@gmail.com'
#google_analytics: 'UA-46278016-1'
#disqus: 'demowebsite'
#sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  will:
    name: Will
    display_name: Will
    gravatar: 
    email: @gmail.com
    web: 
    twitter: 
    description: ""
  caleb:
    name: Caleb
    display_name: Caleb
    gravatar: 
    email: evasivepangolin@gmail.com
    web: 
    twitter: 
    description: "Research and Development Technician"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge